"""
List of plots to produce
"""

#Define a list of intersting plots
Vars = {}
Vars2D = {}
rebin = 2
Vars["Zbb"] = {
    #"boostselectionbestzmassMu":{"name":"boostselectionbestzmassMu","title":"boostselectionbestzmassMu","bin":30,"xmin":76,"xmax":106},
    #"boostselectionbestzmassEle":{"name":"boostselectionbestzmassEle","title":"boostselectionbestzmassEle","bin":30,"xmin":76,"xmax":106},
    #"boostselectionbestzptMu":{"name":"boostselectionbestzptMu","title":"boostselectionbestzptMu","bin":300,"xmin":0,"xmax":1000},
    #"boostselectionbestzptEle":{"name":"boostselectionbestzptEle","title":"boostselectionbestzptEle","bin":300,"xmin":0,"xmax":1000},
    #"boostselectionbestzetaMu":{"name":"boostselectionbestzetaMu","title":"boostselectionbestzetaMu","bin":500,"xmin":-10,"xmax":10},
    #"boostselectionbestzetaEle":{"name":"boostselectionbestzetaEle","title":"boostselectionbestzetaEle","bin":500,"xmin":-10,"xmax":10},
    #"boostselectionbestzphiMu":{"name":"boostselectionbestzphiMu","title":"boostselectionbestzphiMu","bin":800,"xmin":-3.15,"xmax":3.15},
    #"boostselectionbestzphiEle":{"name":"boostselectionbestzphiEle","title":"boostselectionbestzphiEle","bin":800,"xmin":-3.15,"xmax":3.15},
    #"boostselectiondrllMu":{"name":"boostselectiondrllMu","title":"boostselectiondrllMu","bin":50,"xmin":0,"xmax":5},
    #"boostselectiondrllEle":{"name":"boostselectiondrllEle","title":"boostselectiondrllEle","bin":50,"xmin":0,"xmax":5},

    #"boostselectiondijetM":{"name":"boostselectiondijetM","title":"boostselectiondijetM","bin":1500,"xmin":0,"xmax":1500},
    #"boostselectiondijetPt":{"name":"boostselectiondijetPt","title":"boostselectiondijetPt","bin":1000,"xmin":0,"xmax":1000},
    #"boostselectiondijetdR":{"name":"boostselectiondijetdR","title":"boostselectiondijetdR","bin":50,"xmin":0,"xmax":5},
    #"boostselectiondijetEta":{"name":"boostselectiondijetEta","title":"boostselectiondijetEta","bin":500,"xmin":-10,"xmax":10},
    #"boostselectiondijetPhi":{"name":"boostselectiondijetPhi","title":"boostselectiondijetPhi","bin":800,"xmin":-3.15,"xmax":3.15},
    #"detab1b2":{"name":"detab1b2","title":"matrixElementsbjet1etapm-matrixElementsbjet2etapm","bin":100,"xmin":-5,"xmax":5},

    "boostselectionZbbM":{"name":"boostselectionZbbM","title":"boostselectionZbbM","bin":1500,"xmin":0,"xmax":1500},
    #"boostselectionZbbPt":{"name":"boostselectionZbbPt","title":"boostselectionZbbPt","bin":1000,"xmin":0,"xmax":1000},
    #"boostselectiondphiZbb":{"name":"boostselectiondphiZbb","title":"boostselectiondphiZbb","bin":400,"xmin":0,"xmax":3.15},
    #"boostselectiondrZbb":{"name":"boostselectiondrZbb","title":"boostselectiondrZbb","bin":100,"xmin":0,"xmax":10},
    #"boostselectionZbbEta":{"name":"boostselectionZbbEta","title":"boostselectionZbbEta","bin":500,"xmin":-10,"xmax":10},
    #"boostselectionZbbPhi":{"name":"boostselectionZbbPhi","title":"boostselectionZbbPhi","bin":800,"xmin":-3.15,"xmax":3.15},
    #"detaZbbMu":{"name":"detaZbbMu","title":"boostselectionbestzetaMu-boostselectiondijetEta","bin":500,"xmin":-10,"xmax":10},
    #"detaZbbEle":{"name":"detaZbbEle","title":"boostselectionbestzetaEle-boostselectiondijetEta","bin":500,"xmin":-10,"xmax":10},
    #"boostselectionCentrality":{"name":"boostselectionCentrality","title":"boostselectionCentrality","bin":20,"xmin":0,"xmax":1},
    #"boostselectionCentralityBoost":{"name":"boostselectionCentralityBoost","title":"boostselectionCentralityBoost","bin":20,"xmin":0,"xmax":1},

    #"boostselectionCosThetab1":{"name":"boostselectionCosThetab1","title":"boostselectionCosThetab1","bin":10,"xmin":-1,"xmax":1},
    #"boostselectionCosThetal1":{"name":"boostselectionCosThetal1","title":"boostselectionCosThetal1","bin":10,"xmin":-1,"xmax":1},
    #"absCosThetab1":{"name":"absCosThetab1","title":"abs(boostselectionCosThetab1)","bin":10,"xmin":0,"xmax":1},
    #"absCosThetal1":{"name":"absCosThetal1","title":"abs(boostselectionCosThetal1)","bin":10,"xmin":0,"xmax":1},
    #"boostselectionCosThetaStar":{"name":"boostselectionCosThetaStar","title":"boostselectionCosThetaStar","bin":10,"xmin":-1,"xmax":1},
    #"boostselectionPhi1":{"name":"boostselectionPhi1","title":"boostselectionPhi1","bin":10,"xmin":-3.15,"xmax":3.15},
    #"boostselectionPhi":{"name":"boostselectionPhi","title":"boostselectionPhi","bin":10,"xmin":-3.15,"xmax":3.15},

    #"boostselectionZbM":{"name":"boostselectionZbM","title":"boostselectionZbM","bin":1000,"xmin":0,"xmax":1000},
    #"boostselectionZbPt":{"name":"boostselectionZbPt","title":"boostselectionZbPt","bin":1000,"xmin":0,"xmax":1000},

    #"boostselectiondetab1l2":{"name":"boostselectiondetab1l2","title":"boostselectiondetab1l2","bin":50,"xmin":0,"xmax":5},
    #"boostselectiondetab2l1":{"name":"boostselectiondetab2l1","title":"boostselectiondetab2l1","bin":50,"xmin":0,"xmax":5},

    #"jetmetMET":{"name":"jetmetMET","title":"jetmetMET","bin":100,"xmin":0,"xmax":100},
    #"jetmetMETphi":{"name":"jetmetMETphi","title":"jetmetMETphi","bin":800,"xmin":-3.15,"xmax":3.15},
    #"jetmetMETsignificance":{"name":"jetmetMETsignificance","title":"jetmetMETsignificance","bin":40,"xmin":0,"xmax":20},

    #"jetmetnj":{"name":"jetmetnj","title":"jetmetnj","bin":10,"xmin":-0.5,"xmax":9.5},

    #"jetmetbjet1pt":{"name":"jetmetbjet1pt","title":"jetmetbjet1pt","bin":500,"xmin":0,"xmax":500},
    #"jetmetbjet2pt":{"name":"jetmetbjet2pt","title":"jetmetbjet2pt","bin":500,"xmin":0,"xmax":500},
    #"jetmetbjet1eta":{"name":"jetmetbjet1eta","title":"jetmetbjet1eta","bin":240,"xmin":0,"xmax":2.4},
    #"jetmetbjet2eta":{"name":"jetmetbjet2eta","title":"jetmetbjet2eta","bin":240,"xmin":0,"xmax":2.4},
    #"jetmetbjet1CSVdisc":{"name":"jetmetbjet1CSVdisc","title":"jetmetbjet1CSVdisc","bin":100,"xmin":0.679,"xmax":1},
    #"jetmetbjet2CSVdisc":{"name":"jetmetbjet2CSVdisc","title":"jetmetbjet2CSVdisc","bin":100,"xmin":0.679,"xmax":1},
    #"CSVprod":{"name":"CSVprod","title":"jetmetbjet1CSVdisc*jetmetbjet2CSVdisc","bin":10,"xmin":0.679*0.679,"xmax":1},
    #"jetmetbjet1SVmass":{"name":"jetmetbjet1SVmass","title":"jetmetbjet1SVmass","bin":100,"xmin":0,"xmax":6},
    #"jetmetbjet2SVmass":{"name":"jetmetbjet2SVmass","title":"jetmetbjet2SVmass","bin":100,"xmin":0,"xmax":6},
    #"sumSVs":{"name":"sumSVs","title":"jetmetbjet1SVmass+jetmetbjet2SVmass","bin":100,"xmin":0,"xmax":12},
    #"jetmetbjet1nVertHE":{"name":"jetmetbjet1nVertHE","title":"jetmetbjet1nVertHE","bin":5,"xmin":-0.5,"xmax":4.5},
    #"jetmetbjet2nVertHE":{"name":"jetmetbjet2nVertHE","title":"jetmetbjet2nVertHE","bin":5,"xmin":-0.5,"xmax":4.5},
    #"nSVsHE":{"name":"nSVsHE","title":"jetmetbjet1nVertHE+jetmetbjet2nVertHE","bin":10,"xmin":-0.5,"xmax":9.5},
    #"jetmetbjet1nVertHP":{"name":"jetmetbjet1nVertHP","title":"jetmetbjet1nVertHP","bin":5,"xmin":-0.5,"xmax":4.5},
    #"jetmetbjet2nVertHP":{"name":"jetmetbjet2nVertHP","title":"jetmetbjet2nVertHP","bin":5,"xmin":-0.5,"xmax":4.5},
    #"nSVsHP":{"name":"nSVsHP","title":"jetmetbjet1nVertHP+jetmetbjet2nVertHP","bin":10,"xmin":-0.5,"xmax":9.5},
    #"matrixElementsbjet1pt":{"name":"matrixElementsbjet1pt","title":"matrixElementsbjet1pt","bin":25,"xmin":0,"xmax":250},
    #"matrixElementsbjet2pt":{"name":"matrixElementsbjet2pt","title":"matrixElementsbjet2pt","bin":15,"xmin":0,"xmax":150},
    #"matrixElementsbjet1etapm":{"name":"matrixElementsbjet1etapm","title":"matrixElementsbjet1etapm","bin":500,"xmin":-2.5,"xmax":2.5},
    #"matrixElementsbjet2etapm":{"name":"matrixElementsbjet2etapm","title":"matrixElementsbjet2etapm","bin":500,"xmin":-2.5,"xmax":2.5},

    #"matrixElementsmu1pt":{"name":"matrixElementsmu1pt","title":"matrixElementsmu1pt","bin":500,"xmin":0,"xmax":500},
    #"matrixElementsmu2pt":{"name":"matrixElementsmu2pt","title":"matrixElementsmu2pt","bin":500,"xmin":0,"xmax":500},
    #"matrixElementsmu1etapm":{"name":"matrixElementsmu1etapm","title":"matrixElementsmu1etapm","bin":100,"xmin":-2.4,"xmax":2.4},
    #"matrixElementsmu2etapm":{"name":"matrixElementsmu2etapm","title":"matrixElementsmu2etapm","bin":100,"xmin":-2.4,"xmax":2.4},

    #"matrixElementsel1pt":{"name":"matrixElementsel1pt","title":"matrixElementsel1pt","bin":500,"xmin":0,"xmax":500},
    #"matrixElementsel2pt":{"name":"matrixElementsel2pt","title":"matrixElementsel2pt","bin":500,"xmin":0,"xmax":500},
    #"matrixElementsel1etapm":{"name":"matrixElementsel1etapm","title":"matrixElementsel1etapm","bin":100,"xmin":-2.5,"xmax":2.5},
    #"matrixElementsel2etapm":{"name":"matrixElementsel2etapm","title":"matrixElementsel2etapm","bin":100,"xmin":-2.5,"xmax":2.5},

    #"vertexAssociationnvertices":{"name":"vertexAssociationnvertices","title":"vertexAssociationnvertices","bin":60,"xmin":-0.5,"xmax":59.5},

    "MVA":{"name":"MVA","title":"ReadMVA(max(boostselectionbestzptMu,boostselectionbestzptEle),max(boostselectiondrllMu,boostselectiondrllEle),boostselectiondijetPt,boostselectiondijetdR,boostselectionZbbPt,boostselectiondphiZbb,abs(boostselectionCosThetab1),jetmetMET)","bin":25,"xmin":-1,"xmax":1.5},

    #"":{"name":"","title":"","bin":30,"xmin":76,"xmax":106},
}

Vars2D["Zbb"] = [
    #["minjeteta","jetmetjet1pt_etaorder"],
    #["maxjeteta","jetmetjet2pt_etaorder"],
    #["minjeteta","maxjeteta"],
    #["jetmetjet1pt_etaorder","jetmetjet2pt_etaorder"],
    #["boostselectiondijetM","boostselectionZbbM"],
    ]
    

Vars["Zjj"] = {
    #"boostselectionbestzmassMu":{"name":"boostselectionbestzmassMu","title":"boostselectionbestzmassMu","bin":60,"xmin":60,"xmax":120},
    #"boostselectionbestzmassEle":{"name":"boostselectionbestzmassEle","title":"boostselectionbestzmassEle","bin":60,"xmin":60,"xmax":120},
    "boostselectionbestzptMu":{"name":"boostselectionbestzptMu","title":"boostselectionbestzptMu","bin":35,"xmin":0,"xmax":350},
    "boostselectionbestzptEle":{"name":"boostselectionbestzptEle","title":"boostselectionbestzptEle","bin":35,"xmin":0,"xmax":350},
    #"boostselectionbestzetaMu":{"name":"boostselectionbestzetaMu","title":"boostselectionbestzetaMu","bin":50,"xmin":-10,"xmax":10},
    #"boostselectionbestzetaEle":{"name":"boostselectionbestzetaEle","title":"boostselectionbestzetaEle","bin":50,"xmin":-10,"xmax":10},
    #"boostselectionbestzphiMu":{"name":"boostselectionbestzphiMu","title":"boostselectionbestzphiMu","bin":40,"xmin":-3.15,"xmax":3.15},
    #"boostselectionbestzphiEle":{"name":"boostselectionbestzphiEle","title":"boostselectionbestzphiEle","bin":40,"xmin":-3.15,"xmax":3.15},
    "boostselectiondphiZbb":{"name":"boostselectiondphiZbb","title":"boostselectiondphiZbb","bin":20,"xmin":0,"xmax":3.15},
    "boostselectiondrZbb":{"name":"boostselectiondrZbb","title":"boostselectiondrZbb","bin":50,"xmin":0,"xmax":10},
    "boostselectionZbbM":{"name":"boostselectionZbbM","title":"boostselectionZbbM","bin":1000/20,"xmin":0,"xmax":1000},
    #"boostselectionZbbPt":{"name":"boostselectionZbbPt","title":"boostselectionZbbPt","bin":1000/20,"xmin":0,"xmax":1000},
    #"boostselectionZbbEta":{"name":"boostselectionZbbEta","title":"boostselectionZbbEta","bin":50,"xmin":-10,"xmax":10},
    #"boostselectionZbbPhi":{"name":"boostselectionZbbPhi","title":"boostselectionZbbPhi","bin":40,"xmin":-3.15,"xmax":3.15},
    #"boostselectiondphiZbj1":{"name":"boostselectiondphiZbj1","title":"boostselectiondphiZbj1","bin":20,"xmin":0,"xmax":3.15},
    #"detaZbbMu":{"name":"detaZbbMu","title":"boostselectionbestzetaMu-boostselectiondijetEta","bin":50,"xmin":-10,"xmax":10},
    #"detaZbbEle":{"name":"detaZbbEle","title":"boostselectionbestzetaEle-boostselectiondijetEta","bin":50,"xmin":-10,"xmax":10},
    #"dphiZjcentralMu":{"name":"dphiZjcentralMu","title":"(abs(boostselectionbestzphiMu-((jetmetjet1eta<jetmetjet2eta)*jetmetjet1phi+(jetmetjet2eta<jetmetjet1eta)*jetmetjet2phi))>TMath::Pi())*(TMath::TwoPi()-abs(boostselectionbestzphiMu-((jetmetjet1eta<jetmetjet2eta)*jetmetjet1phi+(jetmetjet2eta<jetmetjet1eta)*jetmetjet2phi)))+(abs(boostselectionbestzphiMu-((jetmetjet1eta<jetmetjet2eta)*jetmetjet1phi+(jetmetjet2eta<jetmetjet1eta)*jetmetjet2phi))<=TMath::Pi())*(abs(boostselectionbestzphiMu-((jetmetjet1eta<jetmetjet2eta)*jetmetjet1phi+(jetmetjet2eta<jetmetjet1eta)*jetmetjet2phi)))","bin":20,"xmin":0,"xmax":3.15},
    #"dphiZjcentralEle":{"name":"dphiZjcentralEle","title":"(abs(boostselectionbestzphiEle-((jetmetjet1eta<jetmetjet2eta)*jetmetjet1phi+(jetmetjet2eta<jetmetjet1eta)*jetmetjet2phi))>TMath::Pi())*(TMath::TwoPi()-abs(boostselectionbestzphiEle-((jetmetjet1eta<jetmetjet2eta)*jetmetjet1phi+(jetmetjet2eta<jetmetjet1eta)*jetmetjet2phi)))+(abs(boostselectionbestzphiEle-((jetmetjet1eta<jetmetjet2eta)*jetmetjet1phi+(jetmetjet2eta<jetmetjet1eta)*jetmetjet2phi))<=TMath::Pi())*(abs(boostselectionbestzphiEle-((jetmetjet1eta<jetmetjet2eta)*jetmetjet1phi+(jetmetjet2eta<jetmetjet1eta)*jetmetjet2phi)))","bin":20,"xmin":0,"xmax":3.15},
    #"dphiZjforwMu":{"name":"dphiZjforwMu","title":"(abs(boostselectionbestzphiMu-((jetmetjet1eta>jetmetjet2eta)*jetmetjet1phi+(jetmetjet2eta>jetmetjet1eta)*jetmetjet2phi))>TMath::Pi())*(TMath::TwoPi()-abs(boostselectionbestzphiMu-((jetmetjet1eta>jetmetjet2eta)*jetmetjet1phi+(jetmetjet2eta>jetmetjet1eta)*jetmetjet2phi)))+(abs(boostselectionbestzphiMu-((jetmetjet1eta>jetmetjet2eta)*jetmetjet1phi+(jetmetjet2eta>jetmetjet1eta)*jetmetjet2phi))<=TMath::Pi())*(abs(boostselectionbestzphiMu-((jetmetjet1eta>jetmetjet2eta)*jetmetjet1phi+(jetmetjet2eta>jetmetjet1eta)*jetmetjet2phi)))","bin":20,"xmin":0,"xmax":3.15},
    #"dphiZjforwEle":{"name":"dphiZjforwEle","title":"(abs(boostselectionbestzphiEle-((jetmetjet1eta>jetmetjet2eta)*jetmetjet1phi+(jetmetjet2eta>jetmetjet1eta)*jetmetjet2phi))>TMath::Pi())*(TMath::TwoPi()-abs(boostselectionbestzphiEle-((jetmetjet1eta>jetmetjet2eta)*jetmetjet1phi+(jetmetjet2eta>jetmetjet1eta)*jetmetjet2phi)))+(abs(boostselectionbestzphiEle-((jetmetjet1eta>jetmetjet2eta)*jetmetjet1phi+(jetmetjet2eta>jetmetjet1eta)*jetmetjet2phi))<=TMath::Pi())*(abs(boostselectionbestzphiEle-((jetmetjet1eta>jetmetjet2eta)*jetmetjet1phi+(jetmetjet2eta>jetmetjet1eta)*jetmetjet2phi)))","bin":20,"xmin":0,"xmax":3.15},
    #"boostselectiondrZbj1":{"name":"boostselectiondrZbj1","title":"boostselectiondrZbj1","bin":50,"xmin":0,"xmax":10},
    #"boostselectionZbM":{"name":"boostselectionZbM","title":"boostselectionZbM","bin":1000/20,"xmin":0,"xmax":1000},
    #"boostselectionZbPt":{"name":"boostselectionZbPt","title":"boostselectionZbPt","bin":1000/20,"xmin":0,"xmax":1000},
    #"boostselectionscaldptZbj1":{"name":"boostselectionscaldptZbj1","title":"boostselectionscaldptZbj1","bin":1000/20,"xmin":-500,"xmax":500},
    #"boostselectiondetab1l2":{"name":"boostselectiondetab1l2","title":"boostselectiondetab1l2","bin":20,"xmin":0,"xmax":5},
    #"boostselectiondetab2l1":{"name":"boostselectiondetab2l1","title":"boostselectiondetab2l1","bin":20,"xmin":0,"xmax":5},
    #"jetmetMET":{"name":"jetmetMET","title":"jetmetMET","bin":100/5,"xmin":0,"xmax":100},
    #"jetmetMETphi":{"name":"jetmetMETphi","title":"jetmetMETphi","bin":30,"xmin":-3.15,"xmax":3.15},
    #"jetmetMETsignificance":{"name":"jetmetMETsignificance","title":"jetmetMETsignificance","bin":20,"xmin":0,"xmax":20},
    #"jetmetnj":{"name":"jetmetnj","title":"jetmetnj","bin":10,"xmin":-0.5,"xmax":9.5},
    #"matrixElementsbjet1pt":{"name":"matrixElementsbjet1pt","title":"matrixElementsbjet1pt","bin":25,"xmin":0,"xmax":250},
    #"matrixElementsbjet2pt":{"name":"matrixElementsbjet2pt","title":"matrixElementsbjet2pt","bin":15,"xmin":0,"xmax":150},
    "jetmetjet1pt":{"name":"jetmetjet1pt","title":"jetmetjet1pt","bin":25,"xmin":0,"xmax":250},
    "jetmetjet2pt":{"name":"jetmetjet2pt","title":"jetmetjet2pt","bin":15,"xmin":0,"xmax":150},
    #"jetmetjet1pt_etaorder":{"name":"jetmetjet1pt_etaorder","title":"(jetmetjet1eta<jetmetjet2eta)*jetmetjet1pt+(jetmetjet2eta<jetmetjet1eta)*jetmetjet2pt","bin":50,"xmin":0,"xmax":500},
    #"jetmetjet2pt_etaorder":{"name":"jetmetjet2pt_etaorder","title":"(jetmetjet1eta>jetmetjet2eta)*jetmetjet1pt+(jetmetjet2eta>jetmetjet1eta)*jetmetjet2pt","bin":50,"xmin":0,"xmax":500},
    #"jetmetjet1energy":{"name":"jetmetjet1energy","title":"jetmetjet1energy","bin":40,"xmin":0,"xmax":400},
    #"jetmetjet2energy":{"name":"jetmetjet2energy","title":"jetmetjet2energy","bin":40,"xmin":0,"xmax":400},
    #"matrixElementsbjet1etapm":{"name":"matrixElementsbjet1etapm","title":"matrixElementsbjet1etapm","bin":25,"xmin":-2.5,"xmax":2.5},
    #"matrixElementsbjet2etapm":{"name":"matrixElementsbjet2etapm","title":"matrixElementsbjet2etapm","bin":25,"xmin":-2.5,"xmax":2.5},
    #"detab1b2":{"name":"detab1b2","title":"matrixElementsbjet1etapm-matrixElementsbjet2etapm","bin":25,"xmin":-5,"xmax":5},
    #"jetmetjet1etapm":{"name":"jetmetjet1etapm","title":"jetmetjet1etapm","bin":25,"xmin":-2.5,"xmax":2.5},
    #"jetmetjet2etapm":{"name":"jetmetjet2etapm","title":"jetmetjet2etapm","bin":25,"xmin":-2.5,"xmax":2.5},
    #"minjeteta":{"name":"minjeteta","title":"min(jetmetjet1eta,jetmetjet2eta)","bin":50,"xmin":0,"xmax":2.4},
    #"maxjeteta":{"name":"maxjeteta","title":"max(jetmetjet1eta,jetmetjet2eta)","bin":50,"xmin":0,"xmax":2.4},
    #"matrixElementsmu1pt":{"name":"matrixElementsmu1pt","title":"matrixElementsmu1pt","bin":25,"xmin":0,"xmax":250},
    #"matrixElementsmu2pt":{"name":"matrixElementsmu2pt","title":"matrixElementsmu2pt","bin":15,"xmin":0,"xmax":150},
    #"matrixElementsmu1etapm":{"name":"matrixElementsmu1etapm","title":"matrixElementsmu1etapm","bin":25,"xmin":-2.5,"xmax":2.5},
    #"matrixElementsmu2etapm":{"name":"matrixElementsmu2etapm","title":"matrixElementsmu2etapm","bin":25,"xmin":-2.5,"xmax":2.5},
    #"matrixElementsel1pt":{"name":"matrixElementsel1pt","title":"matrixElementsel1pt","bin":25,"xmin":0,"xmax":250},
    #"matrixElementsel2pt":{"name":"matrixElementsel2pt","title":"matrixElementsel2pt","bin":15,"xmin":0,"xmax":150},
    #"matrixElementsel1etapm":{"name":"matrixElementsel1etapm","title":"matrixElementsel1etapm","bin":25,"xmin":-2.5,"xmax":2.5},
    #"matrixElementsel2etapm":{"name":"matrixElementsel2etapm","title":"matrixElementsel2etapm","bin":25,"xmin":-2.5,"xmax":2.5},
    #"jetmetjet1CSVdisc":{"name":"jetmetjet1CSVdisc","title":"jetmetjet1CSVdisc","bin":10,"xmin":0,"xmax":1},
    #"jetmetjet2CSVdisc":{"name":"jetmetjet2CSVdisc","title":"jetmetjet2CSVdisc","bin":10,"xmin":0,"xmax":1},
    #"jetmetjet1JPdisc":{"name":"jetmetjet1JPdisc","title":"jetmetjet1JPdisc","bin":15,"xmin":0,"xmax":2.5},
    #"jetmetjet2JPdisc":{"name":"jetmetjet2JPdisc","title":"jetmetjet2JPdisc","bin":15,"xmin":0,"xmax":2.5},
    #"jetmetjet1PUIdMva":{"name":"jetmetjet1PUIdMva","title":"jetmetjet1PUIdMva","bin":10,"xmin":0,"xmax":1},
    #"jetmetjet2PUIdMva":{"name":"jetmetjet2PUIdMva","title":"jetmetjet2PUIdMva","bin":10,"xmin":0,"xmax":1},
    #"jetmetjet1PUIdWP":{"name":"jetmetjet1PUIdWP","title":"jetmetjet1PUIdWP","bin":8,"xmin":-0.5,"xmax":7.5},
    #"jetmetjet2PUIdWP":{"name":"jetmetjet2PUIdWP","title":"jetmetjet2PUIdWP","bin":8,"xmin":-0.5,"xmax":7.5},
    #"jetmetjet1beta":{"name":"jetmetjet1beta","title":"jetmetjet1beta","bin":10,"xmin":0,"xmax":1},
    #"jetmetjet2beta":{"name":"jetmetjet2beta","title":"jetmetjet2beta","bin":10,"xmin":0,"xmax":1},
    #"jetmetjet1betaStar":{"name":"jetmetjet1betaStar","title":"jetmetjet1betaStar","bin":10,"xmin":0,"xmax":1},
    #"jetmetjet2betaStar":{"name":"jetmetjet2betaStar","title":"jetmetjet2betaStar","bin":10,"xmin":0,"xmax":1},
    #"jetmetjet1npf":{"name":"jetmetjet1npf","title":"jetmetjet1npf","bin":50,"xmin":-0.5,"xmax":49.5},
    #"jetmetjet2npf":{"name":"jetmetjet2npf","title":"jetmetjet2npf","bin":50,"xmin":-0.5,"xmax":49.5},
    #"jetmetjet1nch":{"name":"jetmetjet1nch","title":"jetmetjet1nch","bin":50,"xmin":-0.5,"xmax":49.5},
    #"jetmetjet2nch":{"name":"jetmetjet2nch","title":"jetmetjet2nch","bin":50,"xmin":-0.5,"xmax":49.5},
    #"jetmetjet1Chf":{"name":"jetmetjet1Chf","title":"jetmetjet1Chf","bin":50,"xmin":0,"xmax":1.5},
    #"jetmetjet2Chf":{"name":"jetmetjet2Chf","title":"jetmetjet2Chf","bin":50,"xmin":0,"xmax":1.5},
    #"jetmetjet1Nhf":{"name":"jetmetjet1Nhf","title":"jetmetjet1Nhf","bin":50,"xmin":0,"xmax":1.5},
    #"jetmetjet2Nhf":{"name":"jetmetjet2Nhf","title":"jetmetjet2Nhf","bin":50,"xmin":0,"xmax":1.5},
    #"jetmetjet1cef":{"name":"jetmetjet1cef","title":"jetmetjet1cef","bin":50,"xmin":0,"xmax":1.5},
    #"jetmetjet2cef":{"name":"jetmetjet2cef","title":"jetmetjet2cef","bin":50,"xmin":0,"xmax":1.5},
    #"jetmetjet1nef":{"name":"jetmetjet1nef","title":"jetmetjet1nef","bin":50,"xmin":0,"xmax":1.5},
    #"jetmetjet2nef":{"name":"jetmetjet2nef","title":"jetmetjet2nef","bin":50,"xmin":0,"xmax":1.5},
    #"jetmetjet1Phf":{"name":"jetmetjet1Phf","title":"jetmetjet1Phf","bin":50,"xmin":0,"xmax":1.5},
    #"jetmetjet2Phf":{"name":"jetmetjet2Phf","title":"jetmetjet2Phf","bin":50,"xmin":0,"xmax":1.5},
    #"jetmetjet1Elf":{"name":"jetmetjet1Elf","title":"jetmetjet1Elf","bin":50,"xmin":0,"xmax":1.5},
    #"jetmetjet2Elf":{"name":"jetmetjet2Elf","title":"jetmetjet2Elf","bin":50,"xmin":0,"xmax":1.5},
    #"jetmetjet1Muf":{"name":"jetmetjet1Muf","title":"jetmetjet1Muf","bin":50,"xmin":0,"xmax":1.5},
    #"jetmetjet2Muf":{"name":"jetmetjet2Muf","title":"jetmetjet2Muf","bin":50,"xmin":0,"xmax":1.5},
    #"jetmetjet1Flavor":{"name":"jetmetjet1Flavor","title":"jetmetjet1Flavor","bin":22,"xmin":-0.5,"xmax":21.5},
    #"jetmetjet2Flavor":{"name":"jetmetjet2Flavor","title":"jetmetjet2Flavor","bin":22,"xmin":-0.5,"xmax":21.5},
    #"boostselectionCentrality":{"name":"boostselectionCentrality","title":"boostselectionCentrality","bin":20,"xmin":0,"xmax":1},
    #"boostselectionCentralityBoost":{"name":"boostselectionCentralityBoost","title":"boostselectionCentralityBoost","bin":20,"xmin":0,"xmax":1},
    "boostselectiondijetM":{"name":"boostselectiondijetM","title":"boostselectiondijetM","bin":50,"xmin":0,"xmax":1000},
    #"boostselectiondijetPt":{"name":"boostselectiondijetPt","title":"boostselectiondijetPt","bin":30,"xmin":0,"xmax":300},
    #"boostselectiondijetEta":{"name":"boostselectiondijetEta","title":"boostselectiondijetEta","bin":50,"xmin":-10,"xmax":10},
    #"boostselectiondijetPhi":{"name":"boostselectiondijetPhi","title":"boostselectiondijetPhi","bin":40,"xmin":-3.15,"xmax":3.15},
    "boostselectiondijetdR":{"name":"boostselectiondijetdR","title":"boostselectiondijetdR","bin":25,"xmin":0,"xmax":5},
    "boostselectiondrllMu":{"name":"boostselectiondrllMu","title":"boostselectiondrllMu","bin":25,"xmin":0,"xmax":5},
    "boostselectiondrllEle":{"name":"boostselectiondrllEle","title":"boostselectiondrllEle","bin":25,"xmin":0,"xmax":5},
    #"vertexAssociationnvertices":{"name":"vertexAssociationnvertices","title":"vertexAssociationnvertices","bin":60,"xmin":-0.5,"xmax":59.5},
    #"":{"name":"","title":"","bin":30,"xmin":76,"xmax":106},
}
